blank_issues_enabled: false
contact_links:
  - name: Discord Support Server
    url: https://discord.gg/cRvunaBzBX
    about: If you are looking for support, please go here. GitHub issues are NOT SUPPORT TICKETS.
