mysql:
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  pass: ''
  db: 'tiramisu'

messages:
  noperm: 'No permission'
  noperm_log: f'User {interactions.user} tried to run "{cmd}" but doesnt have permission!'