storage: sqlite
mysql:
  host: 'localhost'
  port: '3306'
  user: 'tiramisu'
  pass: 'ImACatb0y!'
  db: 'tiramisu'

discord:
  token: 'MTAzNTMyMzc1OTY4ODY3OTQ0NA.Gfbtej.DBm7Y82JguDyFjmEFoUaSzV30LslLj2xiMmwUA'
  testing_guild: 1035313572638638110
  owner: 705150784941064293
  roles:
    staff: 000000000000000000

messages:
  noperm: '**ЁЯЪл No permission**'
  noperm_log: '[[user]] (ID: [[user_id]]) tried to run "[[command]]" but doesnt have permission!'
  error: 'тЪая╕П **An Error Occured!**\n```\n[[error]]\n```\nPlease report this to the devs.'
