mysql:
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  pass: 'Rosebotv3!'
  db: 'tiramisu'
  tables:
    - "admins"

discord:
  token: 'MTAzNTMyMzc1OTY4ODY3OTQ0NA.Gfbtej.DBm7Y82JguDyFjmEFoUaSzV30LslLj2xiMmwUA'
  testing_guild: 1035313572638638110
  roles:
    staff: 1035378549403684864

messages:
  noperm: '**🚫 No permission**'
  noperm_log: 'A user tried to run a command but doesnt have permisson.'

# Note: non-db storage still uses the tables value for what 
#   values need stored.
# WARNING: See docs/local-db.yml!
storage:
  db: False

#cog_submodules:
#  use_cog_submodules: False
#  cog_submodules:
#    - "rsmp"