# 
# Tiramisu Discord Bot
# --------------------
# Configuration File
#

storage: sqlite     # Type of storage to use. sqlite or mysql
mysql:              # Login info when using MySQL
  host: 'localhost'
  port: '3306'
  user: 'tiramisu'
  pass: 'SuperSafePassword123'
  db: 'tiramisu'    # Database to use

bridge:           # Config for Chat Bridge
  enabled: true   # Whether or not to run the bridge
  ip: 0.0.0.0     # IP to run it on
  port: 8765      # Port to run server on

discord:
  token: 'PasteBotTokenHere-from-discord.com/developers' # Your bot token
  testing_guild: 1035313572638638110 # Guild to sync instance management and debugging commands in
  owner: 705150784941064293 # ID of the instance owner. they have complete control over starting/stopping the bot
  co_owners: # List of user IDs that can also start/stop and load/unload cogs
    - 000000000

debug: false

# List of .py files in `cogs/` to NOT load.
# If a file ends in .py and is in `cogs/` it will be loaded by default
cog_dontload:
  - 'bad_example.py'

# Commonly used messages for fetching information
messages:
  noperm: '**🚫 No permission**'
  noperm_log: '[[user]] (ID: [[user_id]]) tried to run "[[command]]" but doesnt have permission!'
  error: '⚠️ **An Error Occured!** ``` [[error]] ``` Please report this to the devs.'