mysql:
  host: 'localhost'
  port: '3306'
  user: 'tiramisu'
  pass: 'passwordSecure'
  db: 'databaseName'
  tables:
    - "admins"

discord:
  token: 'YourBotToken'
messages:
  noperm: 'No permission'
  noperm_log: f'User {interactions.user} tried to run "{cmd}" but doesnt have permission!'

# Note: non-db storage still uses the tables value for what 
#   values need stored.
# WARNING: See docs/local-db.yml!
storage:
  db: False

#cog_submodules:
#  use_cog_submodules: False
#  cog_submodules:
#    #- "rsmp"