# 
# Tiramisu Discord Bot
# --------------------
# Configuration File
#

storage: sqlite     # Type of storage to use. sqlite or mysql
mysql:              # Login info when using MySQL
  host: 'localhost'
  port: '3306'
  user: 'tiramisu'
  pass: 'SuperSafePassword123'
  db: 'tiramisu'    # Database to use

discord:
  token: 'PasteBotTokenHere-from-discord.com/developers' # Your bot token
  testing_guild: 1035313572638638110 # Guild to sync instance management and debugging commands in
  owner: 705150784941064293 # ID of the instance owner. they have complete control over starting/stopping the bot
  co_owners: # List of user IDs that can also start/stop and load/unload cogs
    - 000000000

# If enabled:
# - Enables debugging commands in the testing_guild
# - Shows debug level messages in the log
debug: false

# Enables the `/fizz` slash command and other similar easter eggs
fizzdev=catboy: true

# List of .py files in `cogs/` to NOT load.
# If a file ends in .py and is in `cogs/` it will be loaded by default
cog_dontload:
  - 'bad_example.py'

# Commonly used messages for fetching information
messages:
  noperm: '**🚫 No permission**'
  noperm_log: '[[user]] (ID: [[user_id]]) tried to run "[[command]]" but doesnt have permission!'
  error: '⚠️ **An Error Occured!** ``` [[error]] ``` Please report this to the devs.'

# REST API for REST-Based Modlog submissions
# You must install the `flask` python library for this to work.
# WARNING: this feature is in alpha!
api:
  enabled: false            # Whether or not to enable the API
  ip: 127.0.0.1             # What IP address to bind to
  port: 5006                # What port to listen on
  secret: 'config/secret.txt' # Where to store the secret