mysql:
  host: 'localhost'
  port: '3306'
  user: 'tiramisu'
  pass: 'passwordSecure'

discord:
  token: 'YourBotToken'
messages:
  noperm: 'No permission'
  noperm_log: f'User {interactions.user} tried to run "{cmd}" but doesnt have permission!'