# 
# Tiramisu Discord Bot
# --------------------
# Help Command Contents
#

# NOTE: The `contents:` field should be in discord formatting, as this is the RAW MESSAGE sent to discord.
# NOTE: The `[[BOT]]` placeholder will be replaced with the bot's username on-the-fly.

# Initial Help Menu
main:
  name: Main
  contents: |
    # Help 
    [[BOT]] is a discord bot focused on elegance and simplicity, while still executing all the functions you might need in your discord server.
    This page lists most of the basic functions you need to get started with using [[BOT]]

    ## Admins
    Adminstrators are users you have selected that can change settings for your bot, and perform all moderation actions. Admins can also add and remove other admins.
    If nobody in your discord server is an admin yet, the server owner can add themselves as an admins.

    For information on how to use the `/admin` commands, go to the *Admins* section of the help menu.


    ## Settings
    You can set channels, roles, and change other functionality of the bot with the `/setting` command. Use `/setting get` to check what a setting is currently set to, and use `/setting set` to change that value.
    The first setting you are likely to want to change is the `staff_role` setting. To do so, use the following command:
    ```
    /setting set setting:staff_role value:ROLE
    ```and replace `ROLE` with an @mention of the role you want to use.

    You can see what each setting is for by going to the *Settings* section of the menu.

admin:
  name: Admins
  contents: |
    # Admins Help
    Adminstrators are users you have selected that can change settings for your bot, and perform all moderation actions. Admins can also add and remove other admins.
    If nobody in your discord server is an admin yet, the server owner can add themselves as an admins.

    ## Adding Admins
    To add an admin, use the `/admin add` command. Only other admins and the server owner can add admins.

    ```
    /admin add user:USER
    ```where `USER` is the person you would like to make an admin. 

    ## Removing Admins
    Removing administrators is the same as adding them, except you use the `/admin rm` command instead.
    Optionally, you can specify whether the former administrator should be mentioned in [[BOT]]'s response, with the `mention_user` option.

    ## Listing Admins
    To see who is already an administrator, use the `/admin list` command. Use the `mention_admins` option to specify whether the list should ping the admins or not.

setting:
  name: Settings
  contents: |
    # Settings Help
    You can set channels, roles, and change other functionality of the bot with the `/setting` command. Use `/setting get` to check what a setting is currently set to, and use `/setting set` to change that value.
    
    ## Changing Settings
    To change a setting, for example the `staff_role` setting, use the `/setting set` command, like so:
    ```
    /setting set setting:staff_role value:@Staff
    ```mentioning your staff role with `@Staff`

    ## Checking Settings
    You can check what different settings are currently set to with the `/setting get` command. You can also use `/setting get setting:all` to get a list of all available settings.

    ## Available Settings
    Below is a list of some of the available settings and what they do:

    - `staff_role`: The role for moderators and other staff members. Users with this role can use most moderation commands.

    
