# 
# Tiramisu Discord Bot
# --------------------
# Guild-Specific Settings List
#

settings:
  - 'system_channel'
  - 'announcement_channel'
  - 'announcement_role'
  - 'staff_role'
  - 'modlog_channel'
  - 'bugreports_channel'
  - 'bugreports_questions'
  - 'ip_address'
  - 'ip_text'
  - 'ip_game'
  - 'application_channel'
  - 'ticket_channel'
  - 'log_channel'
  - 'no_points_channels'
  - 'application_channel'
  - 'application_questions'

# Internal data that cannot be changed by the user.
hidden:
  - 'ticket_int'
  - 'application_int'
