# 
# Tiramisu Discord Bot
# --------------------
# Guild-Specific Settings List
#

settings:
  - 'system_channel'
  - 'announcement_channel'
  - 'announcement_role'
  - 'staff_role'
  - 'modlog_channel'
  - 'manual_modlog_channel'
  - 'bugreports_channel'
  - 'bugreports_questions'
  - 'ip_address'
  - 'ip_text'
  - 'ip_game'
  - 'ip_answer_channels'
  - 'ticket_channel'
  - 'transcript_channel'
  - 'log_channel'
  - 'no_points_channels'
  - 'application_channel'
  - 'application_questions'
  - 'new_mod_role'
  - 'creator_role'
  - 'creator_channel'
  - 'creator_ping_role'

# Internal data that cannot be changed by the user.
hidden:
  - 'ticket_int'
  - 'application_int'
