#
# Tiramisu Discord Bot
# --------------------
# Welcome Log Message
#

message:
  - ' '
  - ' ╭──o──╮ Tiramisu Discord Bot'
  - ' ├~~~~~┤ © 2024 Tulip SMP Network et al.'
  - ' ╰─────╯ ------------------------------'
  - '         BSD 3-Clause License'
  - ' '
