#
# Tiramisu Discord Bot
# --------------------
# Welcome Log Message
#

message:
  - ' '
  - ' Tiramisu Discord Bot'
  - ' © 2023 RoseSMP Network et al.'
  - ' -----------------------------'
  - ' BSD 3-Clause License'
  - ' '
