#
# Tiramisu Discord Bot
# --------------------
# Welcome Log Message
#

message:
  - ' '
  - ' ╭──o──╮ Tiramisu Discord Bot'
  - ' ├┈┈┈┈┈┤ © 2023 RoseSMP Network et al.'
  - ' ╰─────╯ -----------------------------'
  - '         BSD 3-Clause License'
  - ' '
